#! /bin/bash

/home/steve/phd/.venv/bin/python3 /home/steve/phd/RedfishMetricsGather/gather.py run --host worker-ilo --username metricsuser --password metricspass --insecure t $( cat /usr/local/bin/urls-worker )