prdcr_add name=worker host=worker type=active xprt=sock port=12345 interval=10000000 offset=50000
prdcr_start name=worker
updtr_add name=policy1 interval=1000000 offset=50000
updtr_prdcr_add name=policy1 regex=worker
updtr_start name=policy1