load name=meminfo
config name=meminfo producer=worker instance=worker/meminfo
start name=meminfo interval=1000000
load name=coretemp
config name=coretemp producer=worker instance=worker/coretemp
start name=coretemp interval=1000000
load name=loadavg
config name=loadavg producer=worker instance=worker/loadavg
start name=loadavg interval=1000000
load name=procnet
config name=procnet producer=worker instance=worker/procnet
start name=procnet interval=1000000
load name=procstat2
config name=procstat2 producer=worker instance=worker/procstat2
start name=procstat2 interval=1000000
load name=vmstat
config name=vmstat producer=worker instance=worker/vmstat
start name=vmstat interval=1000000
